all:
  hosts:
    shrobaserver:
      ansible_host: "shrobaserver"
      ansible_user: "chris"
      ansible_become_password: "{{ shrobaserver_chris_password }}"
      ansible_python_interpreter: "/usr/bin/python3"
